### ISSUE TITLE
Get full test coverage

### ISSUE THREAD

**Issue by mrhn** [Cobiro/validation#12]
Language Rule and Currency rule have untested code, get last coverage percentage, should be easily obtainable since the small scope of the project.

**Comment by mrhn** [comment]
I'm guessing this is not used in production anymore?

**Comment by AJenbo** [comment]
Det bliver stadig brugt, men det gør GitHub issues ikke rigtig så fint nok at du lukker den :)

**Comment by mrhn** [comment]
Så kan det være der skal laves full test coverage 😃

**Comment by AJenbo** [comment]
Det er først på listen efter alt det andet ;)
